name: ml-az-interview-task
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml
      - azureml-mlflow
      - azureml-core
      - pandas
      - scikit-learn
      - matplotlib
      - mlflow
      - xgboost
      - joblib
      - xlrd
      - numpy
      - openpyxl
      - pyyaml
